# Generated by Django 5.2.6 on 2025-09-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.IntegerField(default=0, help_text='Total number of reports')),
                ('pending', models.IntegerField(default=0, help_text='Number of pending reports')),
                ('in_progress', models.IntegerField(default=0, help_text='Number of reports in progress')),
                ('resolved', models.IntegerField(default=0, help_text='Number of resolved reports')),
                ('open_reports', models.IntegerField(default=0, help_text='Number of open reports')),
                ('today_reports', models.IntegerField(default=0, help_text='Reports created today')),
                ('avg_resolution', models.FloatField(default=0.0, help_text='Average resolution time in days')),
                ('top_category', models.CharField(default='', help_text='Most reported category', max_length=100)),
                ('category_data', models.JSONField(default=dict, help_text='Category chart data with labels and values')),
                ('markers', models.JSONField(default=list, help_text='Map markers data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Data',
                'verbose_name_plural': 'Dashboard Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
